### ISSUE TITLE
求大佬帮助

### ISSUE THREAD

**Issue by cq-s** [CarltonHere/auto-cpdaily#1]
学校放假后要求提交请假，请假后本项目就检测不上签到任务了，但实际有任务。自己有西南大学的同学实测下面这个项目可以检测请假的任务，能否请大佬在原有项目上添加一个检测请假任务的功能
https://github.com/F-19-F/SWU-CpDaily

**Comment by CarltonHere** [comment]
后续版本会考虑添加请假后签到

**Comment by CarltonHere** [comment]
已解决
