### ISSUE TITLE
信息收集中必填问题，但是题目可以通过其他题目被隐藏的问题

### ISSUE THREAD

**Issue by vitolyon** [CarltonHere/auto-cpdaily#10]
表单所有题目都是必填（*），但有的单选题目选了否，就会隐藏其他相关题目
如果按往常那样提交表单，会报错：list  out of range

大佬，求救哇

**Comment by CarltonHere** [comment]
不需要填写的题目,value直接写null或者''即可

**Comment by vitolyon** [comment]
感谢大佬￥
