### ISSUE TITLE
qq群公告

### ISSUE THREAD

**Issue by lajibatela** [CarltonHere/auto-cpdaily#11]
求救贴

![qq群](https://user-images.githubusercontent.com/95265966/143983123-1bbc9af0-0400-4e88-a5a6-04415272e38c.PNG)

按图示操作配置了ignore字段，没有效果（本github项目下操作的）

https://github.com/thriving123/fuckTodayStudy  也没了，是有新地址吗大佬，还是我配置不对

![日志](https://user-images.githubusercontent.com/95265966/143984071-7fd47990-22b1-4c7d-bfc1-b6b74b5b4734.PNG)

**Comment by CarltonHere** [comment]
请查阅issue#10
