### ISSUE TITLE
Error:CAS登陆失败,意料之外的错误!

### ISSUE THREAD

**Issue by ShaoliangWan** [CarltonHere/auto-cpdaily#12]
您好，这几天出现这个问题不知如何解决，只好来求问；
自己的帐号可以成功，可是尝试其他同学的帐号时就报错，也试过只跑他的帐号依然报这个错误：
Error:CAS登陆失败,意料之外的错误!
以下是部分日志信息：
2021-12-02 07:05:40 V1.7.0 开始尝试登录账号
Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=fzu HTTP/1.1" 200 None
Starting new HTTPS connection (1): fzu.campusphere.net:443
https://fzu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178
https://fzu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154
https://fzu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0
Starting new HTTP connection (1): id.fzu.edu.cn:80
http://id.fzu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D22ce0c4f2a2643619199eb0843d41c46 HTTP/1.1" 200 None
http://id.fzu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D22ce0c4f2a2643619199eb0843d41c46 HTTP/1.1" 200 None
http://id.fzu.edu.cn:80 "GET /authserver/checkNeedCaptcha.htl?username=091800103 HTTP/1.1" 200 16
http://id.fzu.edu.cn:80 "POST /authserver/login?service=https%3A%2F%2Ffzu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D22ce0c4f2a2643619199eb0843d41c46 HTTP/1.1" 200 None
2021-12-02 07:05:41 V1.7.0 Error:CAS登陆失败,意料之外的错误!

**Comment by CarltonHere** [comment]
您好福州大学没有开放CAS登录权限，无法使用该方案
