### ISSUE TITLE
个人的一点优化建议

### ISSUE THREAD

**Issue by linrusheng123** [CarltonHere/auto-cpdaily#13]
此版本如若腾讯云识别验证码出错（有两成概率） 会直接跳过 进行下一账号的任务 由于是用caslogin 没有登录失败重复登录的代码
按照图示更改红区段代码  记录下报错的内容  更改黄字 可实现验证码识别错误重新尝试
![屏幕截图 2021-12-15 000431](https://user-images.githubusercontent.com/37946749/146035372-4ca3e846-9bf0-451c-994a-ed563f263672.png)

**Comment by linrusheng123** [comment]
多账号用上面方法会导致异常  有一个重复就全体重来
将index.py 改成如下可实现单账号失败即重来单账号


    httpProxy = config['httpProxy'] if 'httpProxy' in config else ''
    for user in config['users']:
        incomplete = True
        Utils.log(
            f"2s后开始执行用户{user['user']['username'] if user['user']['username'] else '默认用户'}的任务"
        )
        sleep(2)
        if config['debug']:
            msg = working(user, httpProxy)
        else:
            while incomplete:
                    try:
                        msg = working(user, httpProxy)
                        ret = True
                    except Exception as e:
                        msg = str(e)
                        ret = False
                    ntm = Utils.getTimeStr()
                    if ret == True:
                        #此处需要注意就算提示成功也不一定是真的成功，以实际为准
                        Utils.log(msg)
                        if 'SUCCESS' in msg:
                            incomplete = False
                            msg = push.sendMsg(
                                '今日校园签到成功通知',
                                '服务器(V%s)于%s尝试签到成功!' % (config['Version'], ntm),
                                user['user'])
                        else:
                            incomplete = False
                            msg = push.sendMsg(
                                '今日校园签到异常通知', '服务器(V%s)于%s尝试签到异常!\n异常信息:%s' %
                                (config['Version'], ntm, msg), user['user'])
                    elif '无效的验证码' in msg:
                        print('无效的验证码')
                        continue
                    else:
                        Utils.log("Error:" + msg)
                        incomplete = False
                        msg = push.sendMsg(
                            '今日校园签到失败通知', '服务器(V%s)于%s尝试签到失败!\n错误信息:%s' %
                            (config['Version'], ntm, msg), user['user'])
                    Utils.log(msg)
    Utils.log("自动化任务执行完毕")

**Comment by CarltonHere** [comment]
您好，脚本对于验证码有长度判断，如果连续错误多次就会抛出错误。为了避免资源过度消耗，仓库版本没有计划添加无尽尝试能力

**Comment by CarltonHere** [comment]
暂不处理

**Comment by iodjjd** [comment]
你可以在一个时间段内执行两次命令，比如11：00执行一次，11：20再执行一次

**Comment by linrusheng123** [comment]
> 你可以在一个时间段内执行两次命令，比如11：00执行一次，11：20再执行一次

@iodjjd  这样还是担心会连续两次腾讯验证码识别失败hhh 因为我这边挂了身边同学的十几个号 所以会出现出错概率还是挺大的 所以我目前使用是上面二楼的哪一段  对for语句的单项结果进行检测  目前我自己使用是没什么问题的    每一个单项用户若验证码出错会单独重复  对其他用户没影响  而且我知道是可以登录成功的  所以使用这个方法  不会出现一直失败一直重复的原因  其实也可以加一个递减的项来使重复次数小于一个设定的值  hhhh  具体方法因人而异了

**Comment by linrusheng123** [comment]
就像作者大大说的  这个作为仓库版本肯定是不适用的  而且每个学校的 “无效的验证码”也是不同的 也需要自己适配 应该只适用于和我一样部署在自己服务器的使用  hhhh

**Comment by huajixiaoyan** [comment]
> 多账号用上面方法会导致异常  有一个重复就全体重来
> 将index.py 改成如下可实现单账号失败即重来单账号
> 
> 
>     httpProxy = config['httpProxy'] if 'httpProxy' in config else ''
>     for user in config['users']:
>         incomplete = True
>         Utils.log(
>             f"2s后开始执行用户{user['user']['username'] if user['user']['username'] else '默认用户'}的任务"
>         )
>         sleep(2)
>         if config['debug']:
>             msg = working(user, httpProxy)
>         else:
>             while incomplete:
>                     try:
>                         msg = working(user, httpProxy)
>                         ret = True
>                     except Exception as e:
>                         msg = str(e)
>                         ret = False
>                     ntm = Utils.getTimeStr()
>                     if ret == True:
>                         #此处需要注意就算提示成功也不一定是真的成功，以实际为准
>                         Utils.log(msg)
>                         if 'SUCCESS' in msg:
>                             incomplete = False
>                             msg = push.sendMsg(
>                                 '今日校园签到成功通知',
>                                 '服务器(V%s)于%s尝试签到成功!' % (config['Version'], ntm),
>                                 user['user'])
>                         else:
>                             incomplete = False
>                             msg = push.sendMsg(
>                                 '今日校园签到异常通知', '服务器(V%s)于%s尝试签到异常!\n异常信息:%s' %
>                                 (config['Version'], ntm, msg), user['user'])
>                     elif '无效的验证码' in msg:
>                         print('无效的验证码')
>                         continue
>                     else:
>                         Utils.log("Error:" + msg)
>                         incomplete = False
>                         msg = push.sendMsg(
>                             '今日校园签到失败通知', '服务器(V%s)于%s尝试签到失败!\n错误信息:%s' %
>                             (config['Version'], ntm, msg), user['user'])
>                     Utils.log(msg)
>     Utils.log("自动化任务执行完毕")
> 
> 

改了这个就不用改caslogin里面的了吧。
