### ISSUE TITLE
请问linux支持哪个版本

### ISSUE THREAD

**Issue by sunshuai12** [CarltonHere/auto-cpdaily#15]
请输入当前脚本运行环境的序号
1) 腾讯云函数
2) 阿里云函数
3) 其他Linux环境
#? 3
即将开始部署标准Linux环境
开始部署系统基础环境
暂不支持该发行版

**Comment by CarltonHere** [comment]
您好，一键部署暂时只支持Debian和Ubuntu及其衍生版本
