### ISSUE TITLE
今日校园版本过低？

### ISSUE THREAD

**Issue by KittyEar** [CarltonHere/auto-cpdaily#23]
START RequestId: d46186b9-83de-48ee-ab43-ba05c370ff72Init Report RequestId: d46186b9-83de-48ee-ab43-ba05c370ff72 Coldstart: 2538ms (PullCode: 176ms InitRuntime: 9ms InitFunction: 2353ms) Memory: 512MB MemUsage: 30.49MB2022-01-16 14:20:44 V1.7.1 自动化任务开始执行
2022-01-16 14:20:44 V1.7.1 10s后开始执行用户3186016003的任务
2022-01-16 14:20:54 V1.7.1 正在获取登录地址
2022-01-16 14:20:54 V1.7.1 开始尝试登录账号
Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=fafu HTTP/1.1" 200 None
Starting new HTTPS connection (1): fafu.campusphere.net:443
https://fafu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178
https://fafu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154
Starting new HTTP connection (1): auth.fafu.edu.cn:80
http://auth.fafu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Ffafu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 200 5525
http://auth.fafu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Ffafu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 200 4972
http://auth.fafu.edu.cn:80 "GET /authserver/needCaptcha.html?username=3186016003 HTTP/1.1" 200 4
2022-01-16 14:20:56 V1.7.1 开始识别验证码
http://auth.fafu.edu.cn:80 "GET /authserver/captcha.html HTTP/1.1" 200 2355
2022-01-16 14:20:56 V1.7.1 识别验证码成功
http://auth.fafu.edu.cn:80 "POST /authserver/login?service=https%3A%2F%2Ffafu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 None
https://fafu.campusphere.net:443 "POST /wec-portal-mobile/client/?ticket=ST-227833-D3euEzFBjJCEKZibOqbL1642314056362-Ppkw-cas HTTP/1.1" 302 154
https://fafu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 404 710
2022-01-16 14:20:57 V1.7.1 开始执行收集任务
https://fafu.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList HTTP/1.1" 200 None
https://fafu.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/detailCollector HTTP/1.1" 200 None
https://fafu.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/getFormFields HTTP/1.1" 200 None
2022-01-16 14:20:58 V1.7.1 正在加密表单数据
2022-01-16 14:20:58 V1.7.1 正在尝试提交数据
https://fafu.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/submitForm HTTP/1.1" 200 None
2022-01-16 14:20:59 V1.7.1 今日校园版本过低，请更新至最新版本！
ERROR RequestId:d46186b9-83de-48ee-ab43-ba05c370ff72 Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 60 seconds","statusCode":433}
END RequestId:d46186b9-83de-48ee-ab43-ba05c370ff72
Report RequestId:d46186b9-83de-48ee-ab43-ba05c370ff72 Duration:60000ms Memory:512MB MemUsage:42.796875MB

**Comment by CarltonHere** [comment]
请拉取最新版再试

**Comment by KittyEar** [comment]
> 请拉取最新版再试

今天刚用的腾讯云  
这行命令  curl -sSO https://raw.fastgit.org/CarltonHere/auto-cpdaily/gh-pages/setup.sh && bash setup.sh
