### ISSUE TITLE
当前IP地址已被今日校园封禁

### ISSUE THREAD

**Issue by sun0225SUN** [CarltonHere/auto-cpdaily#24]
我今天将代码部署到腾讯云函数上，但多测试了几次消息通知😥
总计向今日校园提交了大约5次左右，然后最后一次就被封IP了，阿这。。。。😭
想问下大佬IP被封大概多长时间解封，有其他的方案去更换IP么（新建一个云函数？）
![](https://cdn.jsdelivr.net/gh/sun0225SUN/photos/images/202201172138565.jpg)

**Comment by sun0225SUN** [comment]
我醒悟了，我换个地域再重建一个云函数就好了哇
（我没用过腾讯云的这个服务，不太清楚新建一个云函数后，腾讯云分配的服务器IP会不会变化，我直接换个其他地域的服务器重新部署下应该就好了）

**Comment by toyuni** [comment]
解决了吗

**Comment by hhhllll888** [comment]
> 解决了吗


不说了吗，换地域，换地区部署就可以了。
但是我不知道为啥我换哪个，第一次提交成功，第二次就封禁，之后随机封禁或成功，我心怀爆炸，之后我用自己家旧手机做了一个自动打卡的

**Comment by hhhllll888** [comment]
到现在为止，没有被封禁过

**Comment by sun0225SUN** [comment]
> 解决了吗

裂开，腾讯云函数不是收费了么，收费之后我就直接放在云服务器上的，在宝塔面板上设置定时任务。
之前一直能正常跑，今天突然被封IP了，不会是今日校园的风控机制改了吧，明天看看。

**Comment by sun0225SUN** [comment]
> > 解决了吗
> 
> 
> 不说了吗，换地域，换地区部署就可以了。
> 但是我不知道为啥我换哪个，第一次提交成功，第二次就封禁，之后随机封禁或成功，我心怀爆炸，之后我用自己家旧手机做了一个自动打卡的

哈哈哈，其实你可以试试第三天就好了，我之前就是，第一次正常，第二次被封IP，第三天就好了，但是今天突然被封IP了，笑哭！

**Comment by toyuni** [comment]
我是放在腾讯云函数，今天也是这样



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小孙同学 ***@***.***&gt;
发送时间: 2022年6月30日 21:44
收件人: CarltonHere/auto-cpdaily ***@***.***&gt;
抄送: Metian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 (Issue #24)





  
解决了吗
  
裂开，腾讯云函数不是收费了么，收费之后我就直接放在云服务器上的，在宝塔面板上设置定时任务。
 之前一直能正常跑，今天突然被封IP了，不会是今日校园的风控机制改了吧，明天看看。

**Comment by toyuni** [comment]
有什么解决措施吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小孙同学 ***@***.***&gt;
发送时间: 2022年6月30日 21:44
收件人: CarltonHere/auto-cpdaily ***@***.***&gt;
抄送: Metian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 (Issue #24)





  
解决了吗
  
裂开，腾讯云函数不是收费了么，收费之后我就直接放在云服务器上的，在宝塔面板上设置定时任务。
 之前一直能正常跑，今天突然被封IP了，不会是今日校园的风控机制改了吧，明天看看。

**Comment by toyuni** [comment]
> 

我的换了也不行，第一次出现这种情况

**Comment by hhhllll888** [comment]
我不管，我是旧手机服务器打的。要么就是今日校园接入了ip归属地。这可能是迟早的事

**Comment by toyuni** [comment]
也有可能，希望能找到解决办法

**Comment by hhhllll888** [comment]
> 也有可能，希望能找到解决办法

服务器按照ip来筛选，可能唯一的方法是整代理

**Comment by sun0225SUN** [comment]
> 我不管，我是旧手机服务器打的。要么就是今日校园接入了ip归属地。这可能是迟早的事

我主要是帮同学一起提交的，大概有10个左右，也许现在一个IP一小段时间内只能提交一次了。

**Comment by toyuni** [comment]
云函数能加代理上去吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hhhllll888 ***@***.***&gt;
发送时间: 2022年6月30日 21:55
收件人: CarltonHere/auto-cpdaily ***@***.***&gt;
抄送: Metian ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 (Issue #24)





  
也有可能，希望能找到解决办法
  
服务器按照ip来筛选，可能唯一的方法是整代理

**Comment by hhhllll888** [comment]
> 云函数能加代理上去吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: hhhllll888 ***@***.***&gt; 发送时间: 2022年6月30日 21:55 收件人: CarltonHere/auto-cpdaily ***@***.***&gt; 抄送: Metian ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 (Issue #24) 也有可能，希望能找到解决办法 服务器按照ip来筛选，可能唯一的方法是整代理 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

可以啊，在config里可以设置

**Comment by toyuni** [comment]
> 



> > 云函数能加代理上去吗 发自我的iPhone [...](#) ------------------ 原始邮件 ------------------ 发件人： hhhllll888 _**@**_._**> 发送时间： 2022年6月30日 21：55 收件人： CarltonHere/auto-cpdaily _**@**_.**_> 抄送： Metian _**@**_._**>，评论_**@**_。**_> 主题： Re： [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 （Issue #24） 也有可能，希望能找到解决办法 服务器按照ip来筛选，可能唯一的方法是整代理 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您进行了评论。消息 ID： _**@**_.***>
> 
> 可以啊，在config里可以设置

我去试试

**Comment by Index303** [comment]
> > 
> 
> > > 云函数能加代理上去吗 发自我的iPhone [...](#) ------------------ 原始邮件 ------------------ 发件人： hhhllll888 _**@**_._**> 发送时间： 2022年6月30日 21：55 收件人： CarltonHere/auto-cpdaily _**@**_.**_> 抄送： Metian _**@**_._**>，评论_**@**_。**_> 主题： Re： [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 （Issue #24） 也有可能，希望能找到解决办法 服务器按照ip来筛选，可能唯一的方法是整代理 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您进行了评论。消息 ID： _**@**_.***>
> > 
> > 
> > 可以啊，在config里可以设置
> 
> 我去试试

解决了吗？代理那里是怎么填的

**Comment by toyuni** [comment]
没解决，我也不清楚怎么填，填了很多次都不对



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月3日(星期天) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 (Issue #24)





      
云函数能加代理上去吗 发自我的iPhone ... ------------------ 原始邮件 ------------------ 发件人： hhhllll888 @.&gt; 发送时间： 2022年6月30日 21：55 收件人： CarltonHere/auto-cpdaily _@**._&gt; 抄送： Metian ***@***.***&gt;，评论_@。**&gt; 主题： Re： [CarltonHere/auto-cpdaily] 当前IP地址已被今日校园封禁 （Issue #24） 也有可能，希望能找到解决办法 服务器按照ip来筛选，可能唯一的方法是整代理 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您进行了评论。消息 ID： @.***&gt;
  
可以啊，在config里可以设置
  
我去试试
  
解决了吗？代理那里是怎么填的

**Comment by Jacksong918** [comment]
所以config那里怎么配置代理？

**Comment by 3Yannnn** [comment]
> 我醒悟了，我换个地域再重建一个云函数就好了哇 （我没用过腾讯云的这个服务，不太清楚新建一个云函数后，腾讯云分配的服务器IP会不会变化，我直接换个其他地域的服务器重新部署下应该就好了）

老哥能发我一份脚本吗

**Comment by 3Yannnn** [comment]
> 我醒悟了，我换个地域再重建一个云函数就好了哇 （我没用过腾讯云的这个服务，不太清楚新建一个云函数后，腾讯云分配的服务器IP会不会变化，我直接换个其他地域的服务器重新部署下应该就好了）

老哥 今日校园的脚本能丢我一份吗 求求你了
老哥 今日校园的脚本能丢我一份吗 求求你了
老哥 今日校园的脚本能丢我一份吗 求求你了

**Comment by 3Yannnn** [comment]
老哥 今日校园的脚本能丢我一份吗 求求你了
老哥 今日校园的脚本能丢我一份吗 求求你了
老哥 今日校园的脚本能丢我一份吗 求求你了

**Comment by 3Yannnn** [comment]
老哥 今日校园的脚本能丢我一份吗 求求你了





老哥 今日校园的脚本能丢我一份吗 求求你了

**Comment by 3Yannnn** [comment]
> 我今天将代码部署到腾讯云函数上，但多测试了几次消息通知😥 总计向今日校园提交了大约5次左右，然后最后一次就被封IP了，阿这。。。。😭 想问下大佬IP被封大概多长时间解封，有其他的方案去更换IP么（新建一个云函数？ ） ![](https://camo.githubusercontent.com/f34d6dbed05952502fa8b69ce9ad0e00fa099e4eb197582d20822332749b3c90/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73756e3032323553554e2f70686f746f732f696d616765732f3230323230313137323133383536352e6a7067)

老哥 今日校园的脚本能丢我一份吗 求求你了

**Comment by sun0225SUN** [comment]
？
呃呃呃，这仓库又没删，你直接下载不就好了嘛，再说我们学校都不需要健康打卡了，全国应该统一的吧，不理解，蜜汁操作。

**Comment by sun0225SUN** [comment]
> > 我今天将代码部署到腾讯云函数上，但多测试了几次消息通知😥 总计向今日校园提交了大约5次左右，然后最后一次就被封IP了，阿这。。。。😭 想问下大佬IP被封大概多长时间解封，有其他的方案去更换IP么（新建一个云函数？ ） ![](https://camo.githubusercontent.com/f34d6dbed05952502fa8b69ce9ad0e00fa099e4eb197582d20822332749b3c90/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73756e3032323553554e2f70686f746f732f696d616765732f3230323230313137323133383536352e6a7067)
> 
> 老哥 今日校园的脚本能丢我一份吗 求求你了
> 
> 

？呃呃呃，这仓库又没删，你直接下载不就好了嘛，再说我们学校都不需要健康打卡了，全国应该统一的吧，不理解，蜜汁操作。

**Comment by hhhllll888** [comment]
> 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了

你没用过github？

**Comment by hhhllll888** [comment]
现在今日校园专门封云主机的IP，例如腾讯云，华为云，什么什么云都会封。我是建在旧手机上的。

**Comment by sun0225SUN** [comment]
> 

你们学校还需要健康打开么。。。

**Comment by sun0225SUN** [comment]
> 现在今日校园专门封云主机的IP，例如腾讯云，华为云，什么什么云都会封。我是建在旧手机上的。

你们学校还需要健康打卡么。。。

**Comment by 3Yannnn** [comment]
> > 现在今日校园专门封云主机的IP，例如腾讯云，华为云，什么什么云都会封。 我是建在旧手机上的。
> 
> 你们学校还需要健康打卡么。。。

要啊

**Comment by 3Yannnn** [comment]
> > 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了
> 
> 你没用过github？

好多仓库里的今日校园脚本都没用了 不知道哪个可以用

**Comment by 3Yannnn** [comment]
> > > 我今天将代码部署到腾讯云函数上，但多测试了几次消息通知😥 总计向今日校园提交了大约5次左右，然后最后一次就被封IP了，阿这。。。。😭 想问下大佬IP被封大概多长时间解封，有其他的方案去更换IP么（新建一个云函数？ ） ![](https://camo.githubusercontent.com/f34d6dbed05952502fa8b69ce9ad0e00fa099e4eb197582d20822332749b3c90/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73756e3032323553554e2f70686f746f732f696d616765732f3230323230313137323133383536352e6a7067)
> > 
> > 
> > 老哥 今日校园的脚本能丢我一份吗 求求你了
> 
> ？ 呃呃呃，这仓库又没删，你直接下载不就好了嘛，再说我们学校都不需要健康打卡了，全国应该统一的吧，不理解，蜜汁操作。

好多仓库里的今日校园脚本都没用了

**Comment by 3Yannnn** [comment]
不知道哪个脚本可以用
我有国外的服务器

**Comment by sun0225SUN** [comment]
> > > 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了
> > 
> > 
> > 你没用过github？
> 
> 好多仓库里的今日校园脚本都没用了 不知道哪个可以用

好惨，反正这个现在不能用😂

**Comment by 3Yannnn** [comment]
> > > > 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了
> > > 
> > > 
> > > 你没用过github？
> > 
> > 
> > 好多仓库里的今日校园脚本都没用了 不知道哪个可以用
> 
> 好惨，反正这个现在不能用😂

有没有能用的脚本

**Comment by 3Yannnn** [comment]
帮帮忙呗 真的很需要 有偿求助

**Comment by sun0225SUN** [comment]
> > > > > 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了 老哥 今日校园的脚本能丢我一份吗 求求你了
> > > > 
> > > > 
> > > > 你没用过github？
> > > 
> > > 
> > > 好多仓库里的今日校园脚本都没用了 不知道哪个可以用
> > 
> > 
> > 好惨，反正这个现在不能用😂
> 
> 有没有能用的脚本

不了解，但大概率是没有，即使你现在有国外的服务器（好像国外的更容易被封，我之前用过国外的代理节点），那个验证码还得搞一波，而且还有时效，不太好搞。

**Comment by sun0225SUN** [comment]
> 帮帮忙呗 真的很需要 有偿求助

**Comment by sun0225SUN** [comment]
全国都解封啦，你们还需要打卡，属实不李姐

**Comment by 3Yannnn** [comment]
> 全国都解封啦，你们还需要打卡，属实不李姐

傻逼学校

**Comment by sun0225SUN** [comment]
> 帮帮忙呗 真的很需要 有偿求助

全国都解封啦，你们还需要打卡，属实不李姐
