### ISSUE TITLE
ERROR: No matching distribution found for rsa==4.7.2 (from -r requirements.txt (line 10))

### ISSUE THREAD

**Issue by Ydmy520** [CarltonHere/auto-cpdaily#27]
你好我在运行这个的时候发生错误了.......
pip install -r requirements.txt -t ./ -i https://mirrors.aliyun.com/pypi/simple

ERROR: Could not find a version that satisfies the requirement rsa==4.7.2 (from -r requirements.txt (line 10)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
ERROR: No matching distribution found for rsa==4.7.2 (from -r requirements.txt (line 10))
![fjava_r55r0jDlXn](https://user-images.githubusercontent.com/84400571/155154897-a142b850-d261-4c38-98a8-d03442c4663b.png)

**Comment by Ydmy520** [comment]
这是完整的



[root@192 auto-cpdaily-main]# pip install -r requirements.txt -t ./ -i https://mirrors.aliyun.com/pypi/simple
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting requests==2.25.1
  Using cached https://mirrors.aliyun.com/pypi/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting requests_toolbelt==0.9.1
  Using cached https://mirrors.aliyun.com/pypi/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting tencentcloud_sdk_python==3.0.65
  Using cached https://mirrors.aliyun.com/pypi/packages/d9/19/b7c5fe8eec0dee5665b0a0bdeefbf708e05d76b5e6f8637412af79745b5d/tencentcloud_sdk_python-3.0.65-py2.py3-none-any.whl (768 kB)
Collecting urllib3==1.26.3
  Using cached https://mirrors.aliyun.com/pypi/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting beautifulsoup4==4.9.3
  Using cached https://mirrors.aliyun.com/pypi/packages/1c/d9/8c507915ff962b9e854b477b203c171074f59cce9465dac9f71c2b57ebd6/beautifulsoup4-4.9.3-py2-none-any.whl (115 kB)
Collecting pycryptodome==3.10.1
  Using cached https://mirrors.aliyun.com/pypi/packages/41/6f/70d975f1da4b745a7d0d8d6683eeaff6c0a29aa8e36e11630200c7802859/pycryptodome-3.10.1-cp27-cp27mu-manylinux2010_x86_64.whl (1.9 MB)
Collecting pyDes==2.0.1
  Using cached https://mirrors.aliyun.com/pypi/packages/92/5e/0075a35ea5d307a182b0963900298b209ea2f363ccdd5a27e8cb04c58410/pyDes-2.0.1.tar.gz (9.9 kB)
Collecting PyYAML==5.4.1
  Using cached https://mirrors.aliyun.com/pypi/packages/ba/d4/3cf562876e0cda0405e65d351b835077ab13990e5b92912ef2bf1a2280e0/PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574 kB)
Collecting lxml>=4.6.2
  Using cached https://mirrors.aliyun.com/pypi/packages/82/f7/d0ae1fbd16865ba1403c8c7780f848a00f7182f44dace4f1d3d1d7e4f3e4/lxml-4.8.0-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.5 MB)
ERROR: Could not find a version that satisfies the requirement rsa==4.7.2 (from -r requirements.txt (line 10)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
ERROR: No matching distribution found for rsa==4.7.2 (from -r requirements.txt (line 10))

**Comment by Ydmy520** [comment]
这是完整的




[root@192 auto-cpdaily-main]# pip install -r requirements.txt -t ./ -i https://mirrors.aliyun.com/pypi/simple
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting requests==2.25.1
  Using cached https://mirrors.aliyun.com/pypi/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting requests_toolbelt==0.9.1
  Using cached https://mirrors.aliyun.com/pypi/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting tencentcloud_sdk_python==3.0.65
  Using cached https://mirrors.aliyun.com/pypi/packages/d9/19/b7c5fe8eec0dee5665b0a0bdeefbf708e05d76b5e6f8637412af79745b5d/tencentcloud_sdk_python-3.0.65-py2.py3-none-any.whl (768 kB)
Collecting urllib3==1.26.3
  Using cached https://mirrors.aliyun.com/pypi/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting beautifulsoup4==4.9.3
  Using cached https://mirrors.aliyun.com/pypi/packages/1c/d9/8c507915ff962b9e854b477b203c171074f59cce9465dac9f71c2b57ebd6/beautifulsoup4-4.9.3-py2-none-any.whl (115 kB)
Collecting pycryptodome==3.10.1
  Using cached https://mirrors.aliyun.com/pypi/packages/41/6f/70d975f1da4b745a7d0d8d6683eeaff6c0a29aa8e36e11630200c7802859/pycryptodome-3.10.1-cp27-cp27mu-manylinux2010_x86_64.whl (1.9 MB)
Collecting pyDes==2.0.1
  Using cached https://mirrors.aliyun.com/pypi/packages/92/5e/0075a35ea5d307a182b0963900298b209ea2f363ccdd5a27e8cb04c58410/pyDes-2.0.1.tar.gz (9.9 kB)
Collecting PyYAML==5.4.1
  Using cached https://mirrors.aliyun.com/pypi/packages/ba/d4/3cf562876e0cda0405e65d351b835077ab13990e5b92912ef2bf1a2280e0/PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574 kB)
Collecting lxml>=4.6.2
  Using cached https://mirrors.aliyun.com/pypi/packages/82/f7/d0ae1fbd16865ba1403c8c7780f848a00f7182f44dace4f1d3d1d7e4f3e4/lxml-4.8.0-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.5 MB)
ERROR: Could not find a version that satisfies the requirement rsa==4.7.2 (from -r requirements.txt (line 10)) (from versions: 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 3.0, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.1.4, 3.2, 3.2.2, 3.2.3, 3.3, 3.4, 3.4.1, 3.4.2, 4.0, 4.1.1, 4.2, 4.3, 4.4, 4.5, 4.7.1)
ERROR: No matching distribution found for rsa==4.7.2 (from -r requirements.txt (line 10))

**Comment by CarltonHere** [comment]
请使用pip3命令配置或者直接使用一键部署脚本
