### ISSUE TITLE
验证码识别出错

### ISSUE THREAD

**Issue by Lotus0915** [CarltonHere/auto-cpdaily#28]
报错信息：
2022-02-27 13:26:02 V1.8.1 开始识别验证码

https://authserver.bbgu.edu.cn:443 "GET /authserver/needCaptcha.html?username=1905417102 HTTP/1.1" 200 6

2022-02-27 13:32:31 V1.8.1 开始识别验证码

https://authserver.bbgu.edu.cn:443 "GET /authserver/captcha.html HTTP/1.1" 200 2212

2022-02-27 13:32:31 V1.8.1 Error:'ocrOption'

请问这个问题该如何解决

**Comment by CarltonHere** [comment]
请按照文档配置ocr业务的参数

**Comment by Lotus0915** [comment]
感谢，已成功

**Comment by Ncimi** [comment]
大佬您好，通过您的代码适配我们学校后在信息收集提交表单时会提示：
{"code":"2210010000","message":"DAO层参数空或非法！","wid":null,"hasWindowLocation":null,"windowLocation":null,"score":null}
