### ISSUE TITLE
如何升级程序？

### ISSUE THREAD

**Issue by Eobravo** [CarltonHere/auto-cpdaily#33]
是在云函数的终端里再下一遍setup.py然后覆盖安装么？需不需要备份config.yml呀？

**Comment by hhhllll888** [comment]
额，目前老版本支持server酱等一大堆推送通道，新版本只适配了邮箱，不支持老版本推送通道了，升级的话得重写config.yml的推送部分，表单部分可以不用改（大概），我打算升级了新版本，但是新版本好像还有点问题，不知道作者还要鸽多久，可以不急着升级

**Comment by CarltonHere** [comment]
您好，1.8.5配置文件有所变动，请您根据最新的配置模板重新填写配置
