### ISSUE TITLE
可否加入pushplus推送服务

### ISSUE THREAD

**Issue by JDMJDM1998** [CarltonHere/auto-cpdaily#35]
自己尝试加入pushplus 无果 webapi无法使用

**Comment by hhhllll888** [comment]
Webapi要自己搭建sandmail，额，我用新版本信息提交异常了，用旧版本试试吧

**Comment by CarltonHere** [comment]
您好，apprise支持email、钉钉等推送模式，具体请阅读[APPRISE维基](https://github.com/caronc/apprise/wiki)
如需添加更多途径，可以前往apprise项目页面解决
