### ISSUE TITLE
验证码无法验证

### ISSUE THREAD

**Issue by hh2002sun** [CarltonHere/auto-cpdaily#36]
The SecretId is not found, please ensure that your SecretId is correct.
2022-04-03 10:24:33 V1.8.6 10s后开始执行用户2103060202的任务

2022-04-03 10:24:43 V1.8.6 正在获取登录地址

2022-04-03 10:24:43 V1.8.6 开始尝试登录账号

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=237650c2-30ec-4d11-86d6-32fc44695f30 HTTP/1.1" 200 None

Starting new HTTPS connection (1): sylu.campusphere.net:443

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://sylu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTPS connection (1): authserver.sylu.edu.cn:443

https://authserver.sylu.edu.cn:443 "GET /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D365d5e78dd0a431fa7bf4f8cee437386 HTTP/1.1" 200 None

https://authserver.sylu.edu.cn:443 "GET /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D365d5e78dd0a431fa7bf4f8cee437386 HTTP/1.1" 200 None

https://authserver.sylu.edu.cn:443 "GET /authserver/checkNeedCaptcha.htl?username=2103060202 HTTP/1.1" 200 15

2022-04-03 10:24:45 V1.8.6 开始识别验证码

https://authserver.sylu.edu.cn:443 "GET /authserver/getCaptcha.htl HTTP/1.1" 200 None

2022-04-03 10:24:45 V1.8.6 Error:验证码识别出现问题了The SecretId is not found, please ensure that your SecretId is correct

**Comment by CarltonHere** [comment]
请遵循文档中的指引开通OCR服务并申请密钥，请务必把密钥填入config.yml的对应位置

**Comment by hh2002sun** [comment]
> 请遵循文档中的指引开通OCR服务并申请密钥，请务必把密钥填入config.yml的对应位置

2022-04-03 11:09:59 V1.8.6 10s后开始执行用户2103060202的任务

2022-04-03 11:10:09 V1.8.6 正在获取登录地址

2022-04-03 11:10:09 V1.8.6 开始尝试登录账号

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=237650c2-30ec-4d11-86d6-32fc44695f30 HTTP/1.1" 200 None

Starting new HTTPS connection (1): sylu.campusphere.net:443

Starting new HTTPS connection (1): sylu.campusphere.net:443

Starting new HTTPS connection (1): sylu.campusphere.net:443

Starting new HTTPS connection (1): sylu.campusphere.net:443

Starting new HTTPS connection (1): sylu.campusphere.net:443

Starting new HTTPS connection (1): sylu.campusphere.net:443

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://sylu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTPS connection (1): authserver.sylu.edu.cn:443

https://authserver.sylu.edu.cn:443 "GET /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D79e813a8557f4d88a0d079bd4163927d HTTP/1.1" 200 None

https://authserver.sylu.edu.cn:443 "GET /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D79e813a8557f4d88a0d079bd4163927d HTTP/1.1" 200 None

https://authserver.sylu.edu.cn:443 "GET /authserver/checkNeedCaptcha.htl?username=2103060202 HTTP/1.1" 200 15

2022-04-03 11:10:11 V1.8.6 开始识别验证码

https://authserver.sylu.edu.cn:443 "GET /authserver/getCaptcha.htl HTTP/1.1" 200 None

2022-04-03 11:10:11 V1.8.6 识别验证码成功

https://authserver.sylu.edu.cn:443 "POST /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D79e813a8557f4d88a0d079bd4163927d HTTP/1.1" 401 None

2022-04-03 11:10:11 V1.8.6 Error:

Verification code error

Applying Foxmail.com Defaults

Loaded E-Mail URL: mailtos://3438238320:****@qq.com/?from=3438238320%40qq.com&mode=starttls&smtp=smtp.qq.com&user=3438238320%40qq.com&format=html&overflow=upstream&rto=4.0&cto=15&verify=yes

Notifying 1 service(s) asynchronously.

Email From: Apprise Notifications <3438238320@qq.com>

Email To: 3438238320@qq.com

Login ID: 3438238320@qq.com

Delivery: smtp.qq.com:587

Connecting to remote SMTP server...

Securing connection with STARTTLS...

Applying user credentials...

Sent Email notification to "3438238320@qq.com

**Comment by hhhllll888** [comment]
啊这。。验证失败了，识别到验证码，但是失败了，上面有一段是
Verification code error
这可能得多验证几次

**Comment by hh2002sun** [comment]
最终另外找个正常登录就就解决了，不过还是谢谢你

> 啊这。。验证失败了，识别到验证码，但是失败了，上面有一段是 Verification code error 这可能得多验证几次

**Comment by hh2002sun** [comment]
另外找个手机

> 啊这。。验证失败了，识别到验证码，但是失败了，上面有一段是 Verification code error 这可能得多验证几次
