### ISSUE TITLE
腾讯云云函数运行调试成功但是报错

### ISSUE THREAD

**Issue by mzmm403** [CarltonHere/auto-cpdaily#38]
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?这个是调试成功中日志的报错内容，作者大大快点修啊！急用啊！

**Comment by 02wh12** [comment]
我也这个问题

**Comment by Jupitlove** [comment]
也是有一样的问题

**Comment by 02wh12** [comment]
我用了pip3 install lxml这个命令也不好使0.0

**Comment by hhhllll888** [comment]
腾讯云默认python命令用的是python2版本，用pip uninstall lxml;pip3 uninstall lxml;pip3 install lxml试试？
虽然我也不确定

**Comment by fzf404** [comment]
一样，三天前部署的腾讯云函数一直可用，从昨天起新建云函数会报错，尝试锁定依赖库版本与之前可用的云函数一致，bs4依旧找不到lxml，尝试降低lxml库版本和bs4版本，均不可用，甚至将之前可用的云函数打zip包复制到新建的云函数，依旧不可用，考虑可能是腾讯云函数的问题？改了内核版本还是？之前的云函数还能用，我就没继续排查。

**Comment by CarltonHere** [comment]
腾讯云函数请确保python3.6+环境，建议使用一键部署脚本

**Comment by fzf404** [comment]
目前新部署的云函数是不可用的，三天前部署的是可以的，以下为错误日志

START RequestId: 19276d98-07b9-403a-a31f-cca042fd08dc2022-04-07 11:58:58 V1.8.6 自动化任务开始执行
2022-04-07 11:58:58 V1.8.6 10s后开始执行用户2010020115的任务
2022-04-07 11:59:08 V1.8.6 正在获取登录地址
2022-04-07 11:59:08 V1.8.6 开始尝试登录账号
Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=237650c2-*************-695f30 HTTP/1.1" 200 None
Starting new HTTPS connection (1): sylu.campusphere.net:443
https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178
https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154
https://sylu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0
Starting new HTTPS connection (1): authserver.sylu.edu.cn:443
https://authserver.sylu.edu.cn:443 "GET /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D30c4d457e40b43e88c12e277c55806d3 HTTP/1.1" 200 None
https://authserver.sylu.edu.cn:443 "GET /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D30c4d457e40b43e88c12e277c55806d3 HTTP/1.1" 200 None
**2022-04-07 11:59:10 V1.8.6 Error:Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?**
Applying 163.com Defaults
Loaded E-Mail URL: mailtos://serverfzf404:****@163.com:465/nmdfzf404%40163.com?from=serverfzf404%40163.com&mode=ssl&smtp=smtp.163.com&user=serverfzf404%40163.com&format=html&overflow=upstream&rto=4.0&cto=15&verify=yes
Notifying 1 service(s) asynchronously.
Email From: Apprise Notifications <serverfzf404@163.com>
Email To: nmdfzf404@163.com
Login ID: serverfzf404@163.com
Delivery: smtp.163.com:465
Connecting to remote SMTP server...
Securing connection with SSL...
Applying user credentials...
Sent Email notification to "nmdfzf404@163.com".
2022-04-07 11:59:11 V1.8.6 APPRISE推送消息成功
2022-04-07 11:59:11 V1.8.6 自动化任务执行完毕
Response RequestId: 19276d98-07b9-403a-a31f-cca042fd08dc RetMsg: "Finished"END RequestId: 19276d98-07b9-403a-a31f-cca042fd08dcReport RequestId: 19276d98-07b9-403a-a31f-cca042fd08dc Duration: 12416ms Memory: 128MB MemUsage: 39.44MB

**Comment by CarltonHere** [comment]
请新建一个python3.7环境尝试一下，此报错多出现在腾讯云python3.6环境下

**Comment by hhhllll888** [comment]
python3.7没有云端vscode环境，必须本地测试完成后，打包上传云端

**Comment by CarltonHere** [comment]
> python3.7没有云端vscode环境，必须本地测试完成后，打包上传云端

如果没有全功能ide请删除函数重建，腾讯云函数python3.7已经有全功能ide了
