### ISSUE TITLE
请问一下这是什么原因

### ISSUE THREAD

**Issue by hh2002sun** [CarltonHere/auto-cpdaily#41]
2022-04-10 16:47:26 V1.8.6 自动化任务开始执行

2022-04-10 16:47:26 V1.8.6 10s后开始执行用户2103060213的任务

2022-04-10 16:47:36 V1.8.6 正在获取登录地址

2022-04-10 16:47:36 V1.8.6 开始尝试登录账号

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=237650c2-30ec-4d11-86d6-32fc44695f30 HTTP/1.1" 200 None

Starting new HTTPS connection (1): sylu.campusphere.net:443

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://sylu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTPS connection (1): authserver.sylu.edu.cn:443

2022-04-10 16:47:39 V1.8.6 Error:HTTPSConnectionPool(host='authserver.sylu.edu.cn', port=443): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Dc3552d57ae784c20b24a6bc1cf076f2b (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc7f759160>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Applying Foxmail.com Defaults

Loaded E-Mail URL: mailtos://3438238320:****@qq.com/?from=3438238320%40qq.com&mode=starttls&smtp=smtp.qq.com&user=3438238320%40qq.com&format=html&overflow=upstream&rto=4.0&cto=15&verify=yes

Using selector: EpollSelector

Notifying 1 service(s) asynchronously.

Email From: Apprise Notifications <3438238320@qq.com>

Email To: 3438238320@qq.com

Login ID: 3438238320@qq.com

Delivery: smtp.qq.com:587

Connecting to remote SMTP server...

Securing connection with STARTTLS...

Applying user credentials...

**Comment by hh2002sun** [comment]
START RequestId: 4bde4c58-e974-4c05-9c04-98e2ed898d7c

2022-04-10 18:17:55 V1.8.6 自动化任务开始执行

2022-04-10 18:17:55 V1.8.6 10s后开始执行用户2103060213的任务

2022-04-10 18:18:05 V1.8.6 正在获取登录地址

2022-04-10 18:18:05 V1.8.6 开始尝试登录账号

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=237650c2-30ec-4d11-86d6-32fc44695f30 HTTP/1.1" 200 None

Starting new HTTPS connection (1): sylu.campusphere.net:443

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://sylu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://sylu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTPS connection (1): authserver.sylu.edu.cn:443

ERROR RequestId: 4bde4c58-e974-4c05-9c04-98e2ed898d7c Result: Traceback (most recent call last):   File "/var/user/urllib3/util/connection.py", line 73, in create_connection     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):   File "/var/lang/python3/lib/python3.6/socket.py", line 743, in getaddrinfo     for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name or service not known During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/var/user/urllib3/connectionpool.py", line 706, in urlopen     chunked=chunked,   File "/var/user/urllib3/connectionpool.py", line 382, in _make_request     self._validate_conn(conn)   File "/var/user/urllib3/connectionpool.py", line 1010, in _validate_conn     conn.connect()   File "/var/user/urllib3/connection.py", line 353, in connect     conn = self._new_conn()   File "/var/user/urllib3/connection.py", line 182, in _new_conn     self, "Failed to establish a new connection: %s" % e urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3d2ae42940>: Failed to establish a new connection: [Errno -2] Name or service not known During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/var/user/requests/adapters.py", line 449, in send     timeout=timeout   File "/var/user/urllib3/connectionpool.py", line 756, in urlopen     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]   File "/var/user/urllib3/util/retry.py", line 573, in increment     raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='authserver.sylu.edu.cn', port=443): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D20f8ed6376ce4a94b4bbad29613c3fb3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d2ae42940>: Failed to establish a new connection: [Errno -2] Name or service not known',)) During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 176, in handle     ret = self.real_handler(event, context)   File "/var/user/index.py", line 100, in main_handler     main()   File "/var/user/index.py", line 22, in main     msg = working(user, httpProxy)   File "/var/user/index.py", line 56, in working     wise.login()   File "/var/user/actions/wiseLoginService.py", line 92, in login     self.getLoginUrlBySchoolName()   File "/var/user/actions/wiseLoginService.py", line 66, in getLoginUrlBySchoolName     res = self.session.get(clientUrl, verify=False)   File "/var/user/requests/sessions.py", line 555, in get     return self.request('GET', url, **kwargs)   File "/var/user/requests/sessions.py", line 542, in request     resp = self.send(prep, **send_kwargs)   File "/var/user/requests/sessions.py", line 677, in send     history = [resp for resp in gen]   File "/var/user/requests/sessions.py", line 677, in <listcomp>     history = [resp for resp in gen]   File "/var/user/requests/sessions.py", line 245, in resolve_redirects     **adapter_kwargs   File "/var/user/requests/sessions.py", line 655, in send     r = adapter.send(request, **kwargs)   File "/var/user/requests/adapters.py", line 516, in send     raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='authserver.sylu.edu.cn', port=443): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fsylu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D20f8ed6376ce4a94b4bbad29613c3fb3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3d2ae42940>: Failed to establish a new connection: [Errno -2] Name or service not known',))

END RequestId: 4bde4c58-e974-4c05-9c04-98e2ed898d7c

Report RequestId: 4bde4c58-e974-4c05-9c04-98e2ed898d7c Duration: 20910ms Memory: 128MB MemUsage: 41.04MB

**Comment by CarltonHere** [comment]
您好请检查网络环境，未能复现该问题
