### ISSUE TITLE
任务名称判定的需求

### ISSUE THREAD

**Issue by wyek1n** [CarltonHere/auto-cpdaily#43]
现实背景：学校这几天添加了不同的签到任务，而大部分学生群体只需要签到其中一个。
签到情况：我们只需要签一个，推送签到成功，app内显示未签到。
猜测情况：项目无法根据forms问题挑选任务 / 或许是通过任务顺序进行尝试签到？

需要添加一个任务名称判定，如：
taskname: 学生每日健康打卡

**Comment by CarltonHere** [comment]
已添加该功能，请测试
