### ISSUE TITLE
是否需要加入滑动验证码模块？

### ISSUE THREAD

**Issue by hyx0329** [CarltonHere/auto-cpdaily#47]
之前自己给 Nonebot2 写了个打卡插件，整了一个用 Numpy 实现的滑动验证码解决方案，被 port 到 ceajs 后发现效果真的还可以。我看现在这个项目还没有用滑动验证码，不知道这里需不需要？BTW 我并不清楚 Numpy 在腾讯云函数上负担如何 OvO

https://github.com/hyx0329/nonebot_plugin_anti_cpdaily/blob/dev/anti_cpdaily/anti_cpdaily/slider_captcha.py

Edit: 我授权该项目以 MPL+GPL 双重授权形式利用上述链接所引的验证码模块的代码。

**Comment by CarltonHere** [comment]
您好，感谢issue
之前编写cas逻辑时候发现滑块验证码的学校，都没有禁用验证码接口，仍然可以使用ocr验证码登入，不知道现在该逻辑漏洞有没有修补

**Comment by hyx0329** [comment]
@CarltonHere 感谢认可！
之前有个同学同时挂了几个帐号，导致 OCR 额度飞速消耗。我自己在折腾时，非常不希望自己的程序受限于云服务（除非本身就在云上），就研究了下能不能离线处理好字符验证码或滑动验证码，结果就是发现了这个特殊的滑块匹配方案啦。

另外，我观察到在有些情况下并不需要正确的验证码就能登陆，或许是这个特性让登陆没那么容易失败。

**Comment by CarltonHere** [comment]
明白，欢迎pr解决方案
