### ISSUE TITLE
签到进行后查寝任务进行

### ISSUE THREAD

**Issue by rnadow** [CarltonHere/auto-cpdaily#48]
学校有中午和晚上的定位签到，之后晚上的查寝。
但是表单内都配置时，只运行检测签到任务，查寝任务到点后不运行，提示签到任务未开始。

**Comment by IceTiki** [comment]
> 学校有中午和晚上的定位签到，之后晚上的查寝。
> 但是表单内都配置时，只运行检测签到任务，查寝任务到点后不运行，提示签到任务未开始。

建议截图下配置中的查寝部分(

**Comment by rnadow** [comment]
![image](https://user-images.githubusercontent.com/56780236/164587123-a125ff1c-b80f-4b27-8aaa-3f0a8fb42bb2.png)


> > 学校有中午和晚上的定位签到，之后晚上的查寝。
> > 但是表单内都配置时，只运行检测签到任务，查寝任务到点后不运行，提示签到任务未开始。
> 
> 建议截图下配置中的查寝部分(

**Comment by rnadow** [comment]
> > 学校有中午和晚上的定位签到，之后晚上的查寝。
> > 但是表单内都配置时，只运行检测签到任务，查寝任务到点后不运行，提示签到任务未开始。
> 
> 建议截图下配置中的查寝部分(

以前没有加签到之前查寝都是ok的，加了签到以后，查寝就不执行了，只检测签到了。

**Comment by rnadow** [comment]
应该是我前面配置问题，等晚上看看这次修改之后

**Comment by CarltonHere** [comment]
您好，最新版本添加了formTitle配置项用于选择任务，请您测试后反馈

**Comment by rnadow** [comment]
> 您好，最新版本添加了formTitle配置项用于选择任务，请您测试后反馈

还没有用新版本，旧版本可以使用，先运行签到报错，之后查寝就欧克了，之前可能设置有误，感谢回复。
