### ISSUE TITLE
出错啦！网页中没有找到LoginForm

### ISSUE THREAD

**Issue by RPZ1211** [CarltonHere/auto-cpdaily#50]
作者你好，关于这个问题我想问一下需要修改哪里的代码可以解决
![image](https://user-images.githubusercontent.com/61656099/166690227-4dcab5ec-6a40-4490-913f-7e2e913a9975.png)

**Comment by CarltonHere** [comment]
您好提示该内容表示该项目暂时没有适配您的学校

**Comment by Jaya0455** [comment]
> 

大哥好，Error:出错啦！网页中没有找到LoginForm。我帮我同学一起整的，结果前面几个能签到，后面几个就报这个错误了。我决定不是没有适配学校的原因。

**Comment by Jaya0455** [comment]
个人认为更新一下项目即可，明天再看看效果。😄😄😄

**Comment by Jaya0455** [comment]
仓库5天前更新的，我这个签到已经几个月没更新了，先更新看看。

**Comment by hhhllll888** [comment]
是不是可能登陆次数过多，或者就是你们学校服务器垃圾

**Comment by Jaya0455** [comment]
更新过后还是这样。我早签一共签10个，前5个显示无签到任务 ，后面5个全是网页中没有找到LoginForm。我注释掉前5个，再运行了一遍还是爆同样的问题。先不管了，等我睡一觉起来再运行一遍，看看会不会奇迹发生。如果发生了的话，我就一个签到整5个，服务器先签5个，隔一段时间再去管另外5个。

**Comment by Jaya0455** [comment]
服务器(V1.8.9)于2022-05-08 12:20:45尝试签到失败!错误信息:[出错啦！网页中没有找到LoginForm]Traceback (most recent call last): File "/opt/morning-sign/index.py", line 23, in main msg = working(user, httpProxy) File "/opt/morning-sign/index.py", line 56, in working wise.login() File "/opt/morning-sign/actions/wiseLoginService.py", line 93, in login self.checkLogin() File "/opt/morning-sign/actions/wiseLoginService.py", line 87, in checkLogin self.session.cookies = self.loginEntity.login() File "/opt/morning-sign/actions/casLogin.py", line 49, in login raise Exception('出错啦！网页中没有找到LoginForm')Exception: 出错啦！网页中没有找到LoginForm

刚才又试了一下，原本找不到LoginForm的现在是暂无签到任务。上面是一开始报错的邮件提示。

一下子整10个签到user，容易发生错误。那我就分批次进行，一次进行5个。明天再看看情况。

**Comment by IceTiki** [comment]
发下学校名称，有时间看看你的教务系统x

**Comment by Jaya0455** [comment]
南京晓庄学院，金智教务系统。目前我的解决办法是分批次签到，一批次5个user【批次之间间隔10分钟】，这样子不会发生找不到LoginForm的错误。
