### ISSUE TITLE
[疑问]formTitle字段的表达名称有啥用

### ISSUE THREAD

**Issue by hhhllll888** [CarltonHere/auto-cpdaily#51]
这个配置了表单名称会在之后的推送里推送该字段吗

**Comment by IceTiki** [comment]
用于限定任务。
比如你签到的第一个任务是讲座签到，第二个是每日打卡。
那么你填了formTitle为打卡的任务标题就只打卡，不签讲座。

**Comment by hhhllll888** [comment]
哦，就是筛选选定任务的
