### ISSUE TITLE
指定完成特定的签到任务

### ISSUE THREAD

**Issue by jjking2-12** [CarltonHere/auto-cpdaily#52]
学校多了一个需要二维码的签到任务，每次每日打卡都定位到那个二维码任务去了，没办法普通签到

**Comment by hhhllll888** [comment]
草，这个等大佬开发吧，什么学校，这么奇葩，你这是收集，签到还是查寝

**Comment by IceTiki** [comment]
> 学校多了一个需要二维码的签到任务，每次每日打卡都定位到那个二维码任务去了，没办法普通签到

不是可以限定任务吗(taskname)

**Comment by IceTiki** [comment]
说错了，是formTitle

**Comment by jjking2-12** [comment]
你好，可以私信一下步骤吗。

**Comment by CarltonHere** [comment]
您好，请参考文档和配置文件中的注释增加formTitle字段

**Comment by jjking2-12** [comment]
谢谢
