### ISSUE TITLE
我在酷安上分享了您的项目

### ISSUE THREAD

**Issue by jjking2-12** [CarltonHere/auto-cpdaily#54]
您好，请问我可以在酷安评论区分享您的项目吗？

**Comment by CarltonHere** [comment]
您好，感谢您对我的项目的肯定与支持！
我们的项目拥抱开源的初衷是为了加强python爬虫技术交流，但项目性质特殊且考虑到近期国内防疫形势严峻，为了避免项目恶意使用给防疫工作添堵，还请您尽量不分享不传播，谢谢！

**Comment by jjking2-12** [comment]
好的
