### ISSUE TITLE
错误代码 418错误,当前IP地址已被今日校园封禁

### ISSUE THREAD

**Issue by NewCicada** [CarltonHere/auto-cpdaily#58]
2022-07-04 00:10:14 V1.7.0 开始尝试登录账号
Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=1021375065201546 HTTP/1.1" 200 None
Starting new HTTPS connection (1): hzc.campusphere.net:443
https://hzc.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 418 None
2022-07-04 00:10:16 V1.7.0 Error:418错误,当前IP地址已被今日校园封禁
Starting new HTTPS connection (1): sctapi.ftqq.com:443
https://sctapi.ftqq.com:443 "POST /SCT110832TCdi4BX8vDt7IluywZcCDxarl.send?title=%E4%BB%8A%E6%97%A5%E6%A0%A1%E5%9B%AD%E7%AD%BE%E5%88%B0%E5%A4%B1%E8%B4%A5%E9%80%9A%E7%9F%A5&desp=%E6%9C%8D%E5%8A%A1%E5%99%A8%28V1.7.0%29%E4%BA%8E2022-07-04+00%3A10%3A16%E5%B0%9D%E8%AF%95%E7%AD%BE%E5%88%B0%E5%A4%B1%E8%B4%A5%21%0A%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF%3A418%E9%94%99%E8%AF%AF%2C%E5%BD%93%E5%89%8DIP%E5%9C%B0%E5%9D%80%E5%B7%B2%E8%A2%AB%E4%BB%8A%E6%97%A5%E6%A0%A1%E5%9B%AD%E5%B0%81%E7%A6%81 HTTP/1.1" 200 108

**Comment by Index303** [comment]
samesame

**Comment by dajianghu** [comment]
same

**Comment by H3nryM4** [comment]
同样情况。是腾讯云挂的，多个账号。之后更换腾讯云的另一款机器，即不同ip，第一次尝试仍然提示当前ip封禁。怀疑是封禁了腾讯云所有ip段。有相同情况的希望可以详细叙述下自己的情况。

**Comment by Liberi7** [comment]
阿里云同样也是418

**Comment by CarltonHere** [comment]
签到时间、数量、访问频率等行为异常会触发风控418
