### ISSUE TITLE
验证码验签失败怎么解决

### ISSUE THREAD

**Issue by sun0225SUN** [CarltonHere/auto-cpdaily#75]
如题

**Comment by hhhllll888** [comment]
你有方法了？

**Comment by sun0225SUN** [comment]
此验证码何解🙂🙂
![Screenshot_2022-09-26-19-36-06-480_com.wisedu.cpdaily.jpg](https://user-images.githubusercontent.com/79169717/192267014-114905a4-16ec-44bb-911d-4d05d09ec623.jpg)

**Comment by AirrrB** [comment]
同求

**Comment by hhhllll888** [comment]
每次打卡都有这个验证码吗，我在手机上打卡就不会出现，在服务器打卡就会有验证码，可能开始验证打卡设备，如果有一个新设备登陆账号，可能开始出现验证码，在验证一次后，服务器应该会把这个设备设置为手机设备，以后打卡就不会出现验证码

**Comment by hhhllll888** [comment]
我在autox.js里写了打卡的脚本，但是还是有很多问题，如果写完了，我看看能不能开源

**Comment by fllesser** [comment]
这个是今天加的吗

**Comment by hhhllll888** [comment]
不是今天，前几天就有了
