### ISSUE TITLE
Error:[出错啦！网页中没有找到LoginForm]

### ISSUE THREAD

**Issue by fllesser** [CarltonHere/auto-cpdaily#80]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/64878354/196581484-b06f13f0-3b14-4dde-a0ae-a9e070b9d25f.png">

**Comment by EASTINK** [comment]
（我貌似遇到和你一样的问题） debug 看看是不是学校学工号认证服务的地址停了 最近是Twenty 大部分学校都会关外网

**Comment by fllesser** [comment]
一个多星期了，还是这样

**Comment by fllesser** [comment]
刚刚手动跑了下，好像能用了，哈哈，可能今天下午学校才开的
